// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SWACTPROY.Data;
using System;

namespace SWACTPROY.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180602235242_[xsxsxssx]")]
    partial class xsxsxssx
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SWACTPROY.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ApellidoMaterno");

                    b.Property<string>("ApellidoPaterno");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Direccion");

                    b.Property<int>("Dni");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Nombre");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("Telefono");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("correo");

                    b.Property<string>("direccion");

                    b.Property<string>("documento");

                    b.Property<int>("idRubro");

                    b.Property<string>("idUsuario");

                    b.Property<string>("razonSocial")
                        .HasMaxLength(30);

                    b.Property<int>("telefono");

                    b.Property<string>("tipoEmpresa");

                    b.HasKey("idCliente");

                    b.HasIndex("idRubro");

                    b.HasIndex("idUsuario");

                    b.ToTable("T_Cliente");
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Cotizacion", b =>
                {
                    b.Property<int>("idCotizacion")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("idSolicitud");

                    b.Property<string>("pdfCotizar");

                    b.HasKey("idCotizacion");

                    b.ToTable("T_Cotizacion");
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Rubro", b =>
                {
                    b.Property<int>("idRubro")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("detalleRubro");

                    b.Property<string>("nombreRubro");

                    b.HasKey("idRubro");

                    b.ToTable("T_Rubro");
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Servicio", b =>
                {
                    b.Property<int>("idServicio")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("detalle");

                    b.Property<int>("idRubro");

                    b.Property<string>("nombreServicio");

                    b.HasKey("idServicio");

                    b.HasIndex("idRubro");

                    b.ToTable("T_Servicio");
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Solicitud", b =>
                {
                    b.Property<int>("idSolicitud")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("idCliente");

                    b.Property<string>("nombreServicio")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("idSolicitud");

                    b.HasIndex("idCliente");

                    b.ToTable("T_Solicitud");
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Usuario", b =>
                {
                    b.Property<string>("idUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("apellidomaterno");

                    b.Property<string>("apellidopaterno");

                    b.Property<string>("contraseña");

                    b.Property<string>("direccion");

                    b.Property<int>("dni");

                    b.Property<string>("email");

                    b.Property<string>("estado");

                    b.Property<string>("nombre");

                    b.Property<int>("telefono");

                    b.HasKey("idUsuario");

                    b.ToTable("T_Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SWACTPROY.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SWACTPROY.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SWACTPROY.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SWACTPROY.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Cliente", b =>
                {
                    b.HasOne("SWACTPROY.Models.T_Rubro", "T_Rubro")
                        .WithMany("t_Clientes")
                        .HasForeignKey("idRubro")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SWACTPROY.Models.T_Usuario", "T_Usuario")
                        .WithMany("t_Clientes")
                        .HasForeignKey("idUsuario");
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Servicio", b =>
                {
                    b.HasOne("SWACTPROY.Models.T_Rubro", "T_Rubro")
                        .WithMany("t_Servicios")
                        .HasForeignKey("idRubro")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SWACTPROY.Models.T_Solicitud", b =>
                {
                    b.HasOne("SWACTPROY.Models.T_Cliente", "T_Cliente")
                        .WithMany("t_Solicituds")
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
